name = "skvoshop"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "597c1fefe43cf2f788fb8ef4e6eb1e57"

[[routes]]
pattern = "skvoshop.skvo-space.workers.dev/*"
zone_id = "68317604c5ed80ba27381a079839c9fa"

[build]
command = "npm run build"
cwd = "./"

[[d1_databases]]
binding = "DB"
database_name = "fashion-db"
database_id = "e95366b4-3ebd-440a-b607-f752b64fcb3e"
